<a href="https://colab.research.google.com/github/fendyandersonwang/KNN-UCI_Credit_Card/blob/main/Pacmann_K_NN_UCI_Credit_Card.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Data to Python



```
ID
LIMIT_BAL: Limit balance (credit limit dalam dollar Taiwan)
SEX: gender (1=male, 2-female)
EDUCATION: level of education (1 = graduate school; 2 = university; 3 = high school; 4 = others)
MARRIAGE: Marital status (1 = married; 2 = single; 3 = others)
AGE: Age (in years)
PAY_0 - PAY_6 indicate the payment status over the last 6 months. (-1 = pay duly; 1 = payment delay for one month; 2 = payment delay for two months; â€¦; 8 = payment delay for eight months; 9 = payment delay for nine months and above)
BILL_AMT1 through BILL_AMT6 (remaining amount in bill for each of the last six months)
PAY_AMT_1 through PAY_AMT6 (amount paid in each bill over the last six months)
```

### read data

In [1]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv("UCI_Credit_Card.csv")

In [6]:
data.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,2,2,2,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

## cek banyak observasi

In [7]:
data.shape

# Output
# (Jumlah observasi, jumlah kolom/fitur)

(30000, 25)

## cek & drop data duplikat

In [8]:
# cek data duplicate
duplicate_status = data.duplicated()
duplicate_status

0        False
1        False
2        False
3        False
4        False
         ...
29995    False
29996    False
29997    False
29998    False
29999    False
Length: 30000, dtype: bool

In [9]:
# Cari jumlah data duplikatnya
duplicate_status.sum()

# FALSE = 0 --> kalo tidak duplikat
# TRUE = 1 --> kalo duplikat
# Kalau ada yang duplikat, maka jumlahnya > 0

0

In [12]:
data = data.drop_duplicates()

# Tidak ada yang di-drop karena tidak ada duplikat

### Sanity Check

In [11]:
data.shape

# Selalu sanity check!
# Periksa ulang jumlah observasi

(30000, 25)

## Buat dalam fungsi



```
1. Import data
2. Cek Jumlah observasi dan Jumlah kolom
3. Drop duplicate
4. Cek Jumlah observasi dan Jumlah kolom setelah di-drop
5. Return data setelah di-drop
```

In [19]:
# Kita ingin membuat fungsi yang isi perintahnya sebagai berikut
data = pd.read_csv("UCI_Credit_Card.csv")
print("Data asli            : ", data.shape, "- (#observasi, #kolom)")

data = data.drop_duplicates()
print("Data setelah di-drop : ", data.shape, "- (#observasi, #kolom)")

Data asli            :  (30000, 25) - (#observasi, #kolom)
Data setelah di-drop :  (30000, 25) - (#observasi, #kolom)

In [20]:
def importData(filename):
    """
    Fungsi untuk import data & hapus duplikat
    :param filename: <string> nama file input (format .csv)
    :return df: <pandas dataframe> sampel data
    """

    # read data
    df = pd.read_csv(filename)
    print("Data asli            : ", df.shape, "- (#observasi, #kolom)")

    # drop duplicates
    df = df.drop_duplicates()
    print("Data setelah di-drop : ", df.shape, "- (#observasi, #kolom)")

    return df

# (filename) adalah argumen
# Argumen adalah sebuah variable.
# Jika fungsi tsb. diberi argumen filename = "credit_data.csv",
# maka semua variabel 'filename' di dalam fungsi
# akan berubah menjadi "credit_data.csv"

In [21]:
# input
file_credit = "UCI_Credit_Card.csv"

# panggil fungsi
data = importData(filename = file_credit)

Data asli            :  (30000, 25) - (#observasi, #kolom)
Data setelah di-drop :  (30000, 25) - (#observasi, #kolom)

In [22]:
data.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,2,2,2,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

# Data Preprocessing



```
* Input-Output Split, Train-Test Split
* Processing Categorical
* Imputation, Normalization, Drop Duplicates
```

## input-output split

### data output



```
* Fitur y adalah output variabel dari data marketing
* yang lainnya menjadi input
```

In [23]:
data.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,2,2,2,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [24]:
output_data = data["default.payment.next.month"]

# buat data yang berisi data target
# pilih data dengan nama kolom `default.payment.next.month`, lalu namakan sebagai output_data

In [25]:
output_data.head()

0    1
1    1
2    0
3    0
4    0
Name: default.payment.next.month, dtype: int64

### data input



```
* DATA = INPUT + OUTPUT
* DATA - OUTPUT = INPUT
* Jadi kalau dari data, kita drop VARIABLE OUTPUT, maka tersisa hanya variabel INPUT.
```

In [26]:
input_data = data.drop(["default.payment.next.month"],
                       axis = 1)

In [27]:
input_data.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,689.0,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0
1,2,120000.0,2,2,2,26,-1,2,0,0,...,2682.0,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0
2,3,90000.0,2,2,2,34,0,0,0,0,...,13559.0,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0
3,4,50000.0,2,2,1,37,0,0,0,0,...,49291.0,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,35835.0,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0

## Buat semuanya jadi fungsi



```
* buat output_data
* buat input_data
* return input_data dan output_data
```

In [32]:
# isi perintah yang akan dimasukkan ke dalam fungsi
output_data = data["default.payment.next.month"]
input_data = data.drop("default.payment.next.month",
                       axis = 1)

In [33]:
def extractInputOutput(data,
                       output_column_name):
    """
    Fungsi untuk memisahkan data input dan output
    :param data: <pandas dataframe> data seluruh sample
    :param output_column_name: <string> nama kolom output
    :return input_data: <pandas dataframe> data input
    :return output_data: <pandas series> data output
    """
    # drop data
    output_data = data[output_column_name]
    input_data = data.drop(output_column_name,
                           axis = 1)

    return input_data, output_data

# (data, output_column_name) adalah argumen
# Argumen adalah sebuah variable.
# Jika fungsi tsb. diberi argumen data = credit_data,
# maka semua variabel 'data' di dalam fungsi akan berubah menjadi credit_data

In [34]:
# Jangan sampai salah urutan dalam penempatan return
column_to_drop = ["Unnamed: 0"]
output_column_name = ["default.payment.next.month"]

X, y = extractInputOutput(data = data,
                          output_column_name = output_column_name)

In [35]:
X.head(2)

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,689.0,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0
1,2,120000.0,2,2,2,26,-1,2,0,0,...,2682.0,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0

In [36]:
y.head(2)

   default.payment.next.month
0                           1
1                           1

## cek count value data

In [37]:
for i in X.columns:
    print(i, ":", len(X[i].value_counts()))

ID : 30000
LIMIT_BAL : 81
SEX : 2
EDUCATION : 7
MARRIAGE : 4
AGE : 56
PAY_0 : 11
PAY_2 : 11
PAY_3 : 11
PAY_4 : 11
PAY_5 : 10
PAY_6 : 10
BILL_AMT1 : 22723
BILL_AMT2 : 22346
BILL_AMT3 : 22026
BILL_AMT4 : 21548
BILL_AMT5 : 21010
BILL_AMT6 : 20604
PAY_AMT1 : 7943
PAY_AMT2 : 7899
PAY_AMT3 : 7518
PAY_AMT4 : 6937
PAY_AMT5 : 6897
PAY_AMT6 : 6939

In [38]:
# Check repayment status
repayment_columns = ["PAY_0", "PAY_2", "PAY_3", "PAY_4", "PAY_5", "PAY_6"]

for i in repayment_columns:
    print(X[i].value_counts(normalize=True))

 0    0.491233
-1    0.189533
 1    0.122933
-2    0.091967
 2    0.088900
 3    0.010733
 4    0.002533
 5    0.000867
 8    0.000633
 6    0.000367
 7    0.000300
Name: PAY_0, dtype: float64
 0    0.524333
-1    0.201667
 2    0.130900
-2    0.126067
 3    0.010867
 4    0.003300
 1    0.000933
 5    0.000833
 7    0.000667
 6    0.000400
 8    0.000033
Name: PAY_2, dtype: float64
 0    0.525467
-1    0.197933
-2    0.136167
 2    0.127300
 3    0.008000
 4    0.002533
 7    0.000900
 6    0.000767
 5    0.000700
 1    0.000133
 8    0.000100
Name: PAY_3, dtype: float64
 0    0.548500
-1    0.189567
-2    0.144933
 2    0.105300
 3    0.006000
 4    0.002300
 7    0.001933
 5    0.001167
 6    0.000167
 1    0.000067
 8    0.000067
Name: PAY_4, dtype: float64
 0    0.564900
-1    0.184633
-2    0.151533
 2    0.087533
 3    0.005933
 4    0.002800
 7    0.001933
 5    0.000567
 6    0.000133
 8    0.000033
Name: PAY_5, dtype: float64
 0    0.542867
-1    0.191333
-2    0.163167
 2    0.092200
 3    0.006133
 4    0.001633
 7    0.001533
 6    0.000633
 5    0.000433
 8    0.000067
Name: PAY_6, dtype: float64

In [42]:
# There are some classes of category that doesn't give information enough
# Based on these proportion below, we should grouping some classes:
# PAY_0 : class 4-8 into class 3
# PAY_2 : class 4-8 into class 3, class 1 into class 2
# PAY_3 : class 4-8 into class 3, class 1 into class 2
# PAY_4 : class 4-8 into class 3, class 1 into class 2
# PAY_5 : class 4-8 into class 3
# PAY_6 : class 4-8 into class 3

pay_list_to_3 = ["PAY_0", "PAY_2", "PAY_3", "PAY_4", "PAY_5", "PAY_6"]
pay_list_to_2 = ["PAY_2", "PAY_3", "PAY_4"]

list_set_3 = [4.0, 5.0, 6.0, 7.0, 8.0]

# Convert to 3
for i in pay_list_to_3:
    for j in list_set_3:
        data.loc[data[i] == j, i] = 3.0

# Convert to 2
for i in pay_list_to_2:
    data.loc[data[i] == 1.0, i] = 2.0

In [43]:
for i in repayment_columns:
    print(data[i].value_counts(normalize=True))

 0    0.491233
-1    0.189533
 1    0.122933
-2    0.091967
 2    0.088900
 3    0.015433
Name: PAY_0, dtype: float64
 0    0.524333
-1    0.201667
 2    0.131833
-2    0.126067
 3    0.016100
Name: PAY_2, dtype: float64
 0    0.525467
-1    0.197933
-2    0.136167
 2    0.127433
 3    0.013000
Name: PAY_3, dtype: float64
 0    0.548500
-1    0.189567
-2    0.144933
 2    0.105367
 3    0.011633
Name: PAY_4, dtype: float64
 0    0.564900
-1    0.184633
-2    0.151533
 2    0.087533
 3    0.011400
Name: PAY_5, dtype: float64
 0    0.542867
-1    0.191333
-2    0.163167
 2    0.092200
 3    0.010433
Name: PAY_6, dtype: float64

In [44]:
# Education
# EDUCATION: (1=graduate school, 2=university, 3=high school, 4=others, 5=unknown, 6=unknown)
data["EDUCATION"].value_counts(normalize=True)

2    0.467667
1    0.352833
3    0.163900
5    0.009333
4    0.004100
6    0.001700
0    0.000467
Name: EDUCATION, dtype: float64

In [45]:
# Terdapat kelas bernilai "0.0" yang tidak terdapat di Deskripsi Variabel
# kelas 4-6 pada kategori Education kurang dapat menjelaskan tingkat pendidikan dan sedikitnya informasi yang dapat diberikan
# kelas 0, 4, 5, dan 6 dijadikan satu kelas, yakni others atau kelas 4.0
edu_list_to_4 = [0.0, 5.0, 6.0]

for i in edu_list_to_4:
    data.loc[data['EDUCATION']== i, 'EDUCATION'] = 4.0

In [47]:
# redefine the input and output after change some values of class in repayment and education
X, y = extractInputOutput(data = data,
                          output_column_name = output_column_name)

In [48]:
X.head(2)

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,689.0,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0
1,2,120000.0,2,2,2,26,-1,2,0,0,...,2682.0,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0

## Train-Test Split



```
Kenapa?
  Karena tidak mau overfit data training
  Test data akan menjadi future data
  Kita akan latih model ML di data training, dengan CV (Cross-validation)
  Selanjutnya melakukan evaluasi di data testing
```

In [49]:
# Import train-test splitting library dari sklearn (scikit learn)
from sklearn.model_selection import train_test_split

### Train Test Split Function



```
1. X adalah input
2. y adalah output (target)
3. test_size adalah seberapa besar proporsi data test dari keseluruhan data. Contoh test_size = 0.2 artinya data test akan berisi 20% data.
4. random_state adalah kunci untuk random. Harus di-setting sama. Misal random_state = 123.
5. Output:
  X_train = input dari data training
  X_test = input dari data testing
  y_train = output dari data training
  y_test = output dari data testing
6. Urutan outputnya: X_train, X_test, y_train, y_test. Tidak boleh terbalik
```

[Read More](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html)

In [50]:
# Train test split (75-25)
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size = 0.25,
                                                    random_state = 12)

In [51]:
# Sanity check hasil splitting
print(X_train.shape)
print(X_test.shape)

(22500, 24)
(7500, 24)

In [52]:
# Ratio
X_test.shape[0] / X.shape[0]

# Hasil 0.25 - sesuai dengan test_size kita

0.25